title: "Hongseok's House"
description: >-
  Biostatistics • RWE • Causal Inference • Hobbies
author: Hongseok Kim
email: you@example.com
theme: minima

# Personal site at https://username.github.io
url: ""
baseurl: ""

# Show these in the top nav
header_pages:
  - about.md
  - hobbies.md
  - learning.md
  - thoughts.md

# Three collections
collections:
  hobbies:
    output: true
    permalink: /hobbies/:path/
  learning:
    output: true
    permalink: /learning/:path/
  thoughts:
    output: true
    permalink: /thoughts/:path/

# (Optional) footer social links
minima:
  social_links:
    - platform: github
      user_url: https://github.com/yourusername
