title: Hongseok's House
description: >-
  Biostatistics • RWE • Causal Inference • Hobbies
author: Hongseok Kim
email: you@example.com
theme: minima

# If you ever use a project site (not personal), set baseurl: "/repo-name"
baseurl: ""           # the subpath of your site, e.g. /blog
url: ""               # the base hostname & protocol, e.g. https://yourusername.github.io

# Show pages in the top navigation (works with minima)
header_pages:
  - about.md
  - journal.md
  - hobbies.md

# Collections for separate sections
collections:
  journal:
    output: true
    permalink: /journal/:path/
  hobbies:
    output: true
    permalink: /hobbies/:path/

# Social links (optional; shows in footer for minima)
minima:
  social_links:
    - platform: github
      user_url: https://github.com/yourusername
    - platform: linkedin
      user_url: https://www.linkedin.com/in/your-profile/
